// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjebgesdbaavetemusph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqZWJnZXNkYmFhdmV0ZW11c3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNTczNTYsImV4cCI6MjA1OTczMzM1Nn0.uISP6M6RlnvDchW1kG3ftPD-PDU2oy3WrNAn7OZ_8xU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);